const express = require('express');
const fs = require('fs');
const rawMovies = require('./ket_qua_1500_phim.json');
let javsbMeta={};try{javsbMeta=JSON.parse(fs.readFileSync(require('path').join(__dirname,'javsb_metadata.json'),'utf8'))||{};}catch{}
const metaKey=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const movies = rawMovies.map(m=>{const j=javsbMeta[String(m.code||'').toUpperCase()]||javsbMeta[metaKey(m.code)]||null;if(!j)return m;return {...m,title:j.title||m.title,description:j.description||m.description,actors:Array.isArray(j.actors)&&j.actors.length?j.actors:m.actors,genres:Array.isArray(j.genres)&&j.genres.length?j.genres:m.genres,director:j.director||m.director,runtime:j.runtime||m.runtime||m.duration,releaseInfo:j.releaseDate||m.releaseInfo,studio:j.studio||m.studio,series:j.series||m.series,javsb_url:j.sourceUrl||m.javsb_url};});
const siteCategories = require('./site-categories.json');
const app = express(); const PORT=Number(process.env.PORT||7000); const PAGE_SIZE=100;
const clean=v=>String(v||'').replace(/\s*-\s*VLXX\.COM\s*$/i,'').trim(); const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const normUrl=v=>{try{const u=new URL(v);u.search='';u.hash='';return u.href}catch{return String(v||'')}}; const decodePart=s=>{try{return decodeURIComponent(String(s||''))}catch{return String(s||'')}};
const asList=v=>Array.isArray(v)?v.map(clean).filter(Boolean):String(v||'').split(/[,|]/).map(clean).filter(Boolean); const uniq=a=>[...new Set(a.filter(Boolean))]; const actorKey=name=>norm(name).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); const actorFileKey=name=>norm(name).replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const cats=(siteCategories.categories||[]).map(c=>({name:String(c.name||'').trim(),path:c.path||'',urls:new Set((c.page_urls||[]).map(normUrl))})); const cid=c=>`site_${c.path||Buffer.from(c.name).toString('base64url')}`; const cmap=new Map(cats.map(c=>[cid(c),c])); const genreOptions=cats.map(c=>c.name).filter(Boolean); const actorNames=uniq(movies.flatMap(m=>asList(m.actors))); const actorMap=new Map(actorNames.map(name=>[actorKey(name),name])); const commonExtra=[{name:'genre',isRequired:false,options:genreOptions},{name:'actor',isRequired:false},{name:'skip',isRequired:false},{name:'search',isRequired:false}]; const catalogs=[{type:'movie',id:'xiec_latest_movies',name:'🔥 PHIM SEX MỚI',extra:commonExtra},...cats.map(c=>({type:'movie',id:cid(c),name:c.name,extra:commonExtra}))];
const manifest={id:'community.xemxiec.catalog',version:'1.3.2',name:'XemXiec',description:'XemXiec • Nuvio movie catalog',resources:['catalog','meta','stream'],types:['movie','series'],idPrefixes:['movie_'],behaviorHints:{configurable:false},catalogs}; const categoryGenres=m=>cats.filter(c=>c.urls.has(normUrl(m.page_url))).map(c=>c.name); const movieGenres=m=>uniq([...asList(m.genres),...categoryGenres(m)]); const isVietsub=m=>m.vietsub===true||movieGenres(m).some(g=>norm(g)===norm('Phim sex Vietsub'));
const sceneCache=new Map(),scenePending=new Map(),trailerCache=new Map(),actorImageCache=new Map(),actorPending=new Map();
const PUBLIC_REV='v126'; const publicMovieId=m=>`${m.id}:${PUBLIC_REV}`; const TRAILER_POSTER='https://raw.githubusercontent.com/chuongnguyen89dn-ui/XemXiec/main/ChatGPT%20Image%2016_44_50%2016%20thg%209%2C%202026.png';
function cidCandidates(code){const x=clean(code).toLowerCase().match(/^([a-z]+)[-_ ]?(\d+)$/i);if(!x)return[];const p=x[1],n=x[2];return uniq([`${p}${n.padStart(5,'0')}`,`${p}${n.padStart(4,'0')}`,`${p}${n}`]);}
function javTrailerBases(code){const x=clean(code).toLowerCase().match(/^([a-z]+)[-_ ]?(\d+)$/i);if(!x)return[];const p=x[1],n=String(Number(x[2]));const nums=uniq([n.padStart(5,'0'),n.padStart(4,'0'),n.padStart(3,'0')]);const dirs=uniq([`${p[0]}/${p.slice(0,3)}`,`${p[0]}/${p}`]);return nums.flatMap(num=>dirs.map(dir=>{const c=p+num;return{cid:c,dir,base:`https://media.javtrailers.com/hlsvideo/freepv/${dir}/${c}`,imageBase:`https://images.javtrailers.com/digital/video/${c}`};}));}
function directPoster(code){const x=javTrailerBases(code)[0];return x?`${x.imageBase}/${x.cid}ps.w360.webp`:null;}
async function fetchWithTimeout(url,opts={},ms=1600){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),ms);try{return await fetch(url,{...opts,signal:controller.signal});}finally{clearTimeout(timer);}}
async function discoverTrailer(code){const key=clean(code).toUpperCase();if(!key)return null;if(key==='PGD-932'){const url='https://media.javtrailers.com/litevideo/freepv/p/pgd/pgd00932/pgd00932_dmb_w.mp4';trailerCache.set(key,url);return url;}if(trailerCache.has(key))return trailerCache.get(key);const candidates=javTrailerBases(code).map(x=>`${x.base}/playlist.m3u8`);const checks=candidates.map(async url=>{try{const r=await fetchWithTimeout(url,{redirect:'manual',headers:{'user-agent':'Mozilla/5.0','accept':'application/vnd.apple.mpegurl,application/x-mpegURL,*/*'}},1600);if(r.status!==200)return null;const text=await r.text();return text.trimStart().startsWith('#EXTM3U')?{url,body:text}:null;}catch{return null;}});const results=await Promise.all(checks);const hit=results.find(Boolean)||null;if(!hit){trailerCache.set(key,null);return null;}trailerCache.set(key,hit.url);return hit.url;}
async function validImage(url,referer=''){try{const headers={accept:'image/avif,image/webp,image/apng,image/*,*/*;q=0.8'};if(referer)headers.referer=referer;const r=await fetchWithTimeout(url,{redirect:'manual',headers},1400);if(r.status!==200||!(r.headers.get('content-type')||'').startsWith('image/'))return false;const b=await r.arrayBuffer();return b.byteLength>1000;}catch{return false;}}
async function discoverScenes(code){const key=clean(code).toUpperCase();if(!key)return[];if(sceneCache.has(key))return sceneCache.get(key);if(scenePending.has(key))return scenePending.get(key);const p=(async()=>{for(const x of javTrailerBases(key)){const urls=Array.from({length:30},(_,n)=>`${x.imageBase}/${x.cid}jp-${n+1}.b800.webp`);const out=[];const batchSize=10;for(let start=0;start<urls.length;start+=batchSize){const batch=urls.slice(start,start+batchSize);const ok=await Promise.all(batch.map(u=>validImage(u,'https://javtrailers.com/')));for(let i=0;i<batch.length;i++)if(ok[i])out.push(batch[i]);if(start>=10&&ok.every(v=>!v))break;}if(out.length){sceneCache.set(key,out);return out;}}sceneCache.set(key,[]);return[];})().finally(()=>scenePending.delete(key));scenePending.set(key,p);return p;}
async function discoverActorImage(name){const key=actorKey(name);if(!key)return null;if(actorImageCache.has(key))return actorImageCache.get(key);if(actorPending.has(key))return actorPending.get(key);const p=(async()=>{const file=actorFileKey(name);const candidates=[`https://javmodel.com/javdata/uploads/${file}150.jpg`,`https://javmodel.com/javdata/uploads/${file}.jpg`];for(const url of candidates){if(await validImage(url,`https://javmodel.com/jav/${key}/`)){actorImageCache.set(key,url);return url;}}actorImageCache.set(key,null);return null;})().finally(()=>actorPending.delete(key));actorPending.set(key,p);return p;}
function descriptionOf(m){const d=clean(m.description||''),code=clean(m.code||'');if(!code||norm(d).includes(norm(code)))return d;return `Mã phim: ${code}${d?`\n\n${d}`:''}`;} function actorMetaLink(name){const explicit=clean(process.env.ADDON_MANIFEST_URL||''),renderHost=clean(process.env.RENDER_EXTERNAL_HOSTNAME||''),manifestUrl=explicit||(renderHost?`https://${renderHost}/manifest.json`:'');return manifestUrl?`stremio:///discover/${encodeURIComponent(manifestUrl)}/movie/xiec_latest_movies?actor=${encodeURIComponent(name)}`:`stremio:///search?search=${encodeURIComponent(name)}`;}
function baseMeta(m,scenes=[],trailer=null){const id=publicMovieId(m),genres=movieGenres(m),actors=asList(m.actors),shots=(scenes||[]).filter(Boolean);const hasScenes=shots.length>0;const meta={id,type:'movie',name:`${isVietsub(m)?'🇻🇳 ':''}${clean(m.title)}`,poster:directPoster(m.code)||m.poster||undefined,background:hasScenes?shots[0]:(m.background||m.backdrop||m.preview||undefined),description:descriptionOf(m),website:m.page_url||undefined,posterShape:'poster',behaviorHints:{defaultVideoId:id}};if(genres.length)meta.genres=genres;if(actors.length){meta.cast=actors;meta.links=actors.map(name=>({name,category:'actor',url:actorMetaLink(name)}));}if(m.country)meta.country=Array.isArray(m.country)?m.country.join(', '):clean(m.country);if(m.runtime||m.duration)meta.runtime=clean(m.runtime||m.duration);if(m.releaseInfo||m.year)meta.releaseInfo=String(m.releaseInfo||m.year);if(m.director)meta.director=asList(m.director);if(m.studio)meta.studio=clean(m.studio);if(m.series)meta.series=clean(m.series);if(m.javsb_url)meta.links=[...(meta.links||[]),{name:'JAV.SB',category:'source',url:m.javsb_url}];const released=/^\d{4}-\d{2}-\d{2}/.test(String(m.releaseInfo||''))?`${String(m.releaseInfo).slice(0,10)}T00:00:00.000Z`:'2026-01-01T00:00:00.000Z';const videos=[];if(trailer||shots.length)videos.push({id,title:clean(m.title)||clean(m.code)||'Play',released,available:true});if(trailer)videos.push({id:`${id}:trailer`,title:'Trailer',released,season:1,episode:0,thumbnail:TRAILER_POSTER,overview:`${clean(m.code)} • Trailer`,available:true});shots.forEach((thumbnail,i)=>videos.push({id:`${id}:image:${i+1}`,title:`Snap ${i+1}`,released,season:1,episode:i+1,thumbnail,overview:`${clean(m.code)} • Snap ${i+1}`,available:true}));if(videos.length)meta.videos=videos;return meta;}
function extras(path='',query={}){const out={};for(const p of String(path||'').split('/')){if(!p.includes('='))continue;const[k,...rest]=p.split('=');out[k]=decodePart(rest.join('='));}for(const k of['skip','search','genre','actor'])if(query[k]!==undefined)out[k]=String(query[k]);return out;} function catalogItems(id){if(id==='xiec_latest_movies')return [...movies].sort((a,b)=>(parseInt(String(b.id||'').match(/\d+/)?.[0]||'0',10)-parseInt(String(a.id||'').match(/\d+/)?.[0]||'0',10)));const c=cmap.get(id);return c?movies.filter(m=>c.urls.has(normUrl(m.page_url))):[];} function catalogResponse(id,path,query){const e=extras(path,query);let items=catalogItems(id);if(e.genre){const c=cats.find(x=>x.name===e.genre);if(c)items=items.filter(m=>c.urls.has(normUrl(m.page_url)));}if(e.actor){const a=norm(e.actor);items=items.filter(m=>asList(m.actors).some(x=>norm(x)===a));}const q=norm(e.search||'');if(q)items=items.filter(m=>norm(`${m.title||''} ${m.description||''} ${m.code||''} ${(m.actors||[]).join(' ')}`).includes(q));const skip=Math.max(0,parseInt(e.skip||'0',10)||0);return{metas:items.slice(skip,skip+PAGE_SIZE).map(m=>baseMeta(m,sceneCache.get(clean(m.code).toUpperCase())||m.scene_images||[],trailerCache.get(clean(m.code).toUpperCase())||null))};}
app.get('/trailer-poster.webp',(req,res)=>{res.set('Cache-Control','public, max-age=31536000, immutable');res.type('image/webp');res.sendFile(require('path').join(__dirname,'trailer-poster.webp'));}); app.get('/',(req,res)=>res.json({ok:true,service:'XemXiec',version:'1.3.2',manifest:'/manifest.json'})); app.get('/manifest.json',(req,res)=>res.json(manifest)); app.get('/healthz',(req,res)=>res.json({ok:true,version:'1.3.2',movies:movies.length,sceneCache:sceneCache.size,trailers:trailerCache.size,actorImages:actorImageCache.size,actors:actorNames.length})); app.get('/actors.json',(req,res)=>res.json({actors:actorNames.map(name=>({id:actorKey(name),name,image:actorImageCache.get(actorKey(name))||undefined,count:movies.filter(m=>asList(m.actors).some(x=>norm(x)===norm(name))).length}))})); app.get('/actor/:actor.json',(req,res)=>{const name=actorMap.get(req.params.actor)||decodePart(req.params.actor);return res.json({name,image:actorImageCache.get(actorKey(name))||undefined,...catalogResponse('xiec_latest_movies',`actor=${encodeURIComponent(name)}`,{})});}); app.get('/catalog/:type/:id.json',(req,res)=>res.json(['movie','series'].includes(req.params.type)?catalogResponse(req.params.id,'',req.query):{metas:[]})); app.get('/catalog/:type/:id/:path(*)',(req,res)=>res.json(['movie','series'].includes(req.params.type)?catalogResponse(req.params.id,String(req.params.path||'').replace(/\.json$/i,''),req.query):{metas:[]}));
app.get('/meta/:type/:id.json',async(req,res)=>{res.set('Cache-Control','no-store, no-cache, must-revalidate');if(!['movie','series'].includes(req.params.type))return res.json({meta:null});const baseId=String(req.params.id).split(':')[0];const m=movies.find(x=>x.id===baseId);if(!m)return res.json({meta:null});const [trailer,liveScenes]=await Promise.all([m.code?discoverTrailer(m.code):null,m.code?discoverScenes(m.code):[]]);const scenes=liveScenes.length?liveScenes:(Array.isArray(m.scene_images)?m.scene_images:[]);return res.json({meta:baseMeta(m,scenes,trailer)});});
app.get('/stream/:type/:id.json',async(req,res)=>{if(!['movie','series'].includes(req.params.type))return res.json({streams:[]});const rawId=String(req.params.id),baseId=rawId.split(':')[0];const m=movies.find(x=>x.id===baseId);if(!m)return res.json({streams:[]});if(rawId.includes(':image:'))return res.json({streams:[]});if(rawId.endsWith(':trailer')){const trailer=m.code?await discoverTrailer(m.code):null;return res.json({streams:trailer?[{name:'XemXiec Trailer',title:`🎬 Trailer • ${clean(m.code)}`,url:trailer,behaviorHints:{notWebReady:true}}]:[]});}const streams=[],seen=new Set();for(const s of m.streams||[]){if(!s?.url||seen.has(s.url))continue;seen.add(s.url);streams.push({name:'XemXiec',title:`XemXiec • ${s.name||`Nguồn ${streams.length+1}`}`,url:s.url,behaviorHints:{notWebReady:true}});}if(m.manifest_url&&!seen.has(m.manifest_url)){seen.add(m.manifest_url);streams.push({name:'XemXiec',title:`XemXiec • ${streams.length?'Nguồn chính':'#1'}`,url:m.manifest_url,behaviorHints:{notWebReady:true}});}if(m.mp4_url&&!seen.has(m.mp4_url))streams.push({name:'XemXiec',title:'Xiec • MP4',url:m.mp4_url});return res.json({streams});});
async function warmMedia(){for(const m of movies){if(!m.code)continue;await Promise.all([discoverTrailer(m.code),discoverScenes(m.code)]);await new Promise(r=>setTimeout(r,50));}} async function warmActors(){for(const name of actorNames){await discoverActorImage(name);await new Promise(r=>setTimeout(r,50));}}
app.listen(PORT,'0.0.0.0',()=>{console.log(`XemXiec addon v1.3.2 on ${PORT} movies=${movies.length} actor-image-scan=OFF javsb=${Object.keys(javsbMeta).length}`);});